version: '2'
services: 
  osticket:
    build: .
    ports:
     - "8080:8080"
    links:
     - mysql:mysql   
     - memcached:memcached
    environment:
       USE_MEMCACHE: y
    container_name: osticket
    
  mysql:
    image: mysql
    restart: always     
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpw
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: mysecretpw
    container_name: mysql_osticket
    
  memcached:
    image: bitnami/memcached:latest
    restart: always
    container_name: memcached_osticket      

 
