version: '2'
services: 
  osticket:
    image: matiasvictor/docker-osticket
   # build: .
    ports:
     - "80:80"
    links:
     - mysql:mysql   
     - memcached:memcached
    environment:
      MEMCACHE_SERVERS: 11212
      USE_MEMCACHE: y

  mysql:
    image: mysql
    restart: always     
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpw
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: mysecretpw

  memcached:
    image: bitnami/memcached:latest
    restart: always
          

 
